In [29]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [13]:
import numpy as np

lambda_mat = np.full((3,3), 0)
lambda_mat[1,1] = 1
print(lambda_mat)

[[0 0 0]
 [0 1 0]
 [0 0 0]]


In [3]:
from Model.InteractionNode import InteractionNode

In [17]:
print("===")
print("Product={}, PriceLevel={}, Bought={}, #Units={}".format(2,3,"Si",45))


l21 = InteractionNode(3, 4, 0, 0, [])
l22 = InteractionNode(2, 1, 0, 0, [])
l1 = InteractionNode(1, 2, 1, 34, [l21,l22])

l1.printInteractions()

===
Product=2, PriceLevel=3, Bought=Si, #Units=45

USER INTERACTIONS: 
╚═ Product=1, PriceLevel=2, Bought=Yes, #Units=34
  ╚═ Product=3, PriceLevel=4, Bought=No, #Units=0
  ╚═ Product=2, PriceLevel=1, Bought=No, #Units=0


In [19]:
import numpy as np
np.random.uniform(low=0.0, high=1.0, size=None)

0.27985094518957787

In [ ]:
import pprint
import sys
import unittest
from Model.GraphProbabilities import GraphProbabilities
from Model.Product import Product
from Model.UserClass import UserClass
from Model.constants import PROBABILITY_MATRIX, SECONDARY_PRODUCTS

id = 0
conversionRate = [
    [1, 0.3, 0.9, 0.2],
    [1, .2, .56, .12],
    [1, .34, .57, .88],
    [1, .2, .56, .12],
    [1, 0.9, 0.17, 0.96]
]

PROBABILITY_MATRIX_3 = [[0, 1, 1, 0, 0],
                      [0.8, 0, 0, 0.9, 0],
                      [0, 1, 0, 0.7, 0],
                      [0.9, 0, 0, 0, 0],
                      [0, 0, 0, 0, 0]]
clickProbability = GraphProbabilities(PROBABILITY_MATRIX_3)
alphas = [1,0,0,0,0]

n_bought_mean = 2
n_bought_variance = 1
n_user_mean = 10
n_user_variance = 1

productList = [Product(int(key), SECONDARY_PRODUCTS[key]) for key in SECONDARY_PRODUCTS]

Lambda = 1

userClass = UserClass(id=id, conversionRate=conversionRate, clickProbability=clickProbability, alphas=alphas,
                        Lambda=Lambda, n_bought_variance=n_bought_variance, n_bought_mean=n_bought_mean,
                        n_user_mean=n_user_mean, n_user_variance=n_user_variance, productList=productList,
                        features_generator=[{"name":"Over 18","probability":0.6},{"name":"Male","probability":0.9}],
                        debug=False)

# pp = pprint.PrettyPrinter(indent=4)
# pp.pprint(userClass.__dict__)

currentPrice = [0, 0, 0, 0, 0]
userClass.setCurrentPrice(currentPrice)

userInteractions = userClass.generateEpisode()
userInteractions.printInteractions()

In [8]:
click_prob_matrix = [[0, .8, .7, 0, 0],
            [0, 0, 0, .9, .8],
            [0, 1, 0, .75, 0],
            [.9, 0, 0, 0, .82],
            [0, 0, .87, .92, 0]]
click_prob_matrix = np.array(click_prob_matrix).tolist()
print(click_prob_matrix)

[[0.0, 0.8, 0.7, 0.0, 0.0], [0.0, 0.0, 0.0, 0.9, 0.8], [0.0, 1.0, 0.0, 0.75, 0.0], [0.9, 0.0, 0.0, 0.0, 0.82], [0.0, 0.0, 0.87, 0.92, 0.0]]


In [ ]:
def yummy(time, env):
    print("Time: {}".format(time))
    print("Env: {}".format(env.Lambda))
from Environment import Environment
e = Environment(0.3, [userClass])
e.addTimeListener(2, yummy)
e.addTimeListener(2, yummy)
e.round()

In [2]:
from Model.GraphProbabilities import GraphProbabilities
from Model.Product import Product
from Model.UserClass import UserClass
from Model.Evaluator.GraphEvaluator import GraphEvaluator
import numpy as np

CLICK_PROB = [[0, .8, .7, 0, 0],
            [0, 0, 0, .9, .8],
            [0, 1, 0, .75, 0],
            [.9, 0, 0, 0, .82],
            [0, 0, .87, .92, 0]]
L = 0.5
LAMBDA_MATRIX = [[0, 1, L, 0, 0],
                [0, 0, 0, L, 1],
                [0, L, 0, 1, 0],
                [L, 0, 0, 0, 1],
                [0, 0, 1, L, 0]]
conversionRate = [
    [0.9, 0.9, 0.9, 0.9, 0.9],
    [.62, .62, .62, .62, .62],
    [.82, .82, .82, .82, .82],
    [.56, .56, .56, .56, .56],
    [.92, 0.92, 0.92, 0.92, .92]
]
convRates = [.9, .62, .82, .56, .92]
alphas = [0.2, 0.1, 0.3, 0.1, 0.3]
SECONDARY_PRODUCTS = {'0': [1, 2], '1': [4, 3], '2': [3, 1], '3': [4, 0], '4': [2, 3]}
margins = [12,7,9,19,5]

w_matrix = GraphProbabilities(CLICK_PROB)
lambda_matrix = GraphProbabilities(LAMBDA_MATRIX)
conv_matrix = GraphProbabilities(conversionRate)
y_matrix = w_matrix.multiplyElementWise(lambda_matrix)
y_matrix = y_matrix.multiplyElementWise(conv_matrix)

productList = [Product(int(key), SECONDARY_PRODUCTS[key]) for key in SECONDARY_PRODUCTS]
eval = GraphEvaluator(products_list=productList, click_prob_matrix=CLICK_PROB, lambda_prob=0.7, conversion_rates=convRates,
                    alphas=alphas, margins=margins, verbose=True)
print("Expected profit over all interactions: {}".format(eval.computeMargin()))

profitSingle = np.multiply(np.array(alphas),np.multiply(np.array(margins),np.array(convRates))).sum()
print("Expected profit over single products: {}".format(profitSingle))

[[0.0, 0.6480000000000001, 0.19845, 0.0, 0.0], [0.0, 0.0, 0.0, 0.121086, 0.30752], [0.0, 0.23533999999999997, 0.0, 0.5043, 0.0], [0.09878400000000002, 0.0, 0.0, 0.0, 0.25715200000000005], [0.0, 0.0, 0.736368, 0.2725408, 0.0]]
Reached nodes in 1-step: 1; 2; 
Reached nodes in 2-step: 1; 3; 4; 
Reached nodes in 3-step: 2; 3; 4; 
Reached nodes in 4-step: 2; 3; 4; 
Expected value margin for product 0 as starting is 26 

Reached nodes in 1-step: 3; 4; 
Reached nodes in 2-step: 0; 2; 3; 4; 
Reached nodes in 3-step: 0; 2; 3; 
Reached nodes in 4-step: 0; 2; 
Expected value margin for product 1 as starting is 33 

Reached nodes in 1-step: 1; 3; 
Reached nodes in 2-step: 0; 3; 4; 
Reached nodes in 3-step: 0; 1; 3; 4; 
Reached nodes in 4-step: 0; 4; 
Expected value margin for product 2 as starting is 30 

Reached nodes in 1-step: 0; 4; 
Reached nodes in 2-step: 1; 2; 
Reached nodes in 3-step: 1; 4; 
Reached nodes in 4-step: 2; 4; 
Expected value margin for product 3 as starting is 27 

Reached nod

In [1]:
from Model.GraphProbabilities import GraphProbabilities
from Model.Evaluator.GraphEvaluator import GraphEvaluator
from Model.Product import Product
from Model.UserClass import UserClass
import numpy as np

CLICK_PROB = [[0, .8, .7, 0, 0],
            [0, 0, 0, .9, .8],
            [0, 1, 0, .75, 0],
            [.9, 0, 0, 0, .82],
            [0, 0, .87, .92, 0]]
L = 0.5
convRates = [.9, .62, .82, .56, .92]
alphas = [0.2, 0.1, 0.3, 0.1, 0.3]
SECONDARY_PRODUCTS = {'0': [1, 2], '1': [4, 3], '2': [3, 1], '3': [4, 0], '4': [2, 3]}
margins = [12,7,9,19,5]

productList = [Product(int(key), SECONDARY_PRODUCTS[key]) for key in SECONDARY_PRODUCTS]
eval = GraphEvaluator(products_list=productList, click_prob_matrix=CLICK_PROB, lambda_prob=0.7, conversion_rates=convRates,
                    alphas=alphas, margins=margins, verbose=False)
print("Expected profit over all interactions: {}".format(eval.computeMargin()))

profitSingle = np.multiply(np.array(alphas),np.multiply(np.array(margins),np.array(convRates))).sum()
print("Expected profit over single products: {}".format(profitSingle))

Expected profit over all interactions: 30.1
Expected profit over single products: 7.252


In [5]:
from Learner.GreedyLearner import *

conversionRateLevels = [
    [1, 0.8, 0.6, 0.4],
    [1, 0.8, 0.6, 0.4],
    [1, 0.8, 0.6, 0.4],
    [1, 0.8, 0.6, 0.4],
    [1, 0.8, 0.6, 0.4]
]

marginsPerPrice = [[1, 2, 3, 4],  # Product 1
                   [1, 0, 0, 0],  # Product 2
                   [1, 2, 3, 4],  # Product 3
                   [1, 2, 3, 4],  # Product 4
                   [1, 2, 50, 100]  # Product 5
                   ]

gLearner = GreedyLearner()
optimal_arm = []

for i in range(0, 300):
    pulledArm = gLearner.pull_arm()
    margins = []
    convRates = []
    for k in range(0,len(pulledArm)):
        margins.append(marginsPerPrice[k][pulledArm[k]])
        convRates.append(conversionRateLevels[k][pulledArm[k]])

    price_configuration_margin = 0
    eval = GraphEvaluator(products_list=productList, click_prob_matrix=CLICK_PROB, lambda_prob=0.7, conversion_rates=convRates,
                    alphas=alphas, margins=margins, verbose=False)

    overall_margin = eval.computeMargin()
    print("Configuration {}; ConvRates {}; Margins {}; Overall Margin {}".format(pulledArm,convRates,margins,overall_margin))
    gLearner.update(overall_margin)


Configuration [0, 0, 0, 0, 0]; ConvRates [1, 1, 1, 1, 1]; Margins [1, 1, 1, 1, 1]; Overall Margin 4.0
Configuration [1, 0, 0, 0, 0]; ConvRates [0.8, 1, 1, 1, 1]; Margins [2, 1, 1, 1, 1]; Overall Margin 4.0
Configuration [0, 1, 0, 0, 0]; ConvRates [1, 0.8, 1, 1, 1]; Margins [1, 0, 1, 1, 1]; Overall Margin 3.1
Configuration [0, 0, 1, 0, 0]; ConvRates [1, 1, 0.8, 1, 1]; Margins [1, 1, 2, 1, 1]; Overall Margin 4.0
Configuration [0, 0, 0, 1, 0]; ConvRates [1, 1, 1, 0.8, 1]; Margins [1, 1, 1, 2, 1]; Overall Margin 4.0
Configuration [0, 0, 0, 0, 1]; ConvRates [1, 1, 1, 1, 0.8]; Margins [1, 1, 1, 1, 2]; Overall Margin 4.0
Configuration [2, 0, 0, 0, 0]; ConvRates [0.6, 1, 1, 1, 1]; Margins [3, 1, 1, 1, 1]; Overall Margin 4.0
Configuration [1, 1, 0, 0, 0]; ConvRates [0.8, 0.8, 1, 1, 1]; Margins [2, 0, 1, 1, 1]; Overall Margin 3.1
Configuration [1, 0, 1, 0, 0]; ConvRates [0.8, 1, 0.8, 1, 1]; Margins [2, 1, 2, 1, 1]; Overall Margin 4.5
Configuration [1, 0, 0, 1, 0]; ConvRates [0.8, 1, 1, 0.8, 1]; 